const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
function selectTab(name){$$('.titlebar nav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));$$('.tab').forEach(x=>x.classList.toggle('active',x.id===name));}
$$('[data-tab]').forEach(b=>b.addEventListener('click',()=>selectTab(b.dataset.tab)));
$('.close')?.addEventListener('click',()=>window.fluxStudio?.close());$('.min')?.addEventListener('click',()=>window.fluxStudio?.minimize());$('.max')?.addEventListener('click',()=>window.fluxStudio?.maximize());
const code=$('#code'),preview=$('#preview'),consoleEl=$('#console');
function run(){const src=code.value;preview.replaceChildren();preview.style.background='';const bg=src.match(/ui background\s+["'](.+?)["']/i);if(bg)preview.style.background=bg[1];const win=src.match(/ui window\s+["'](.+?)["']/i);if(win){const h=document.createElement('h2');h.textContent=win[1];preview.appendChild(h)}for(const m of src.matchAll(/ui text\s+["'](.+?)["']/gi)){const p=document.createElement('p');p.textContent=m[1];preview.appendChild(p)}for(const m of src.matchAll(/ui button\s+["'](.+?)["']/gi)){const b=document.createElement('button');b.textContent=m[1];b.addEventListener('click',()=>consoleEl.textContent+=`\n${m[1]} clicked`);preview.appendChild(b)}const says=[...src.matchAll(/say\s+["'](.+?)["']/gi)];consoleEl.textContent=says.map(x=>x[1]).join('\n')||'Flux visual preview ready.'}
$('#run')?.addEventListener('click',run);code?.addEventListener('input',run);run();
$('#newProject')?.addEventListener('click',()=>{code.value='ui window "My Flux Project"\nui background "#0a0d14"\nui text "Welcome to Flux."\nui button "Start"\n    colour "#8b5cf6"\ndone\n\nsay "Flux is running!"';selectTab('playground');run()});
const savedAccent=localStorage.getItem('fluxAccent')||'#8b5cf6';document.documentElement.style.setProperty('--accent',savedAccent);const savedTheme=localStorage.getItem('fluxTheme')||'dark';document.documentElement.dataset.theme=savedTheme;
function addAppearanceControls(){const appearance=$$('.cards article')[0];if(!appearance||appearance.querySelector('#themeSelect'))return;const select=document.createElement('select');select.id='themeSelect';select.innerHTML='<option value="dark">Dark glass</option><option value="light">Light glass</option><option value="system">System</option>';select.value=savedTheme;select.addEventListener('change',()=>{localStorage.setItem('fluxTheme',select.value);document.documentElement.dataset.theme=select.value});appearance.appendChild(select);const label=document.createElement('label');label.textContent=' Accent';const picker=document.createElement('input');picker.type='color';picker.id='accentPicker';picker.value=savedAccent;picker.addEventListener('input',()=>{localStorage.setItem('fluxAccent',picker.value);document.documentElement.style.setProperty('--accent',picker.value)});appearance.append(label,picker)}addAppearanceControls();
function showExtensionStudio(){const name=sessionStorage.getItem('fluxExtensionUser');$('#extensionLoggedOut').hidden=!!name;$('#extensionLoggedIn').hidden=!name;if(name){$('#accountName').textContent=name;renderExtensions()}}function renderExtensions(){const list=$('#extensionList');if(!list)return;const items=JSON.parse(localStorage.getItem('fluxExtensions')||'[]');list.replaceChildren();if(!items.length){const p=document.createElement('p');p.textContent='No extensions yet. Create your first one.';list.appendChild(p)}items.forEach(x=>{const d=document.createElement('div');d.className='extension-card';const b=document.createElement('b');b.textContent=x.name;const s=document.createElement('span');s.textContent=x.description||'FluxStudio extension';d.append(b,s);list.appendChild(d)})}
$$('.authbuttons button').forEach(btn=>btn.addEventListener('click',async()=>{const status=$('#authStatus');if(status)status.textContent=`Opening ${btn.dataset.provider} sign-in…`;const result=await window.fluxStudio?.signIn(btn.dataset.provider);if(status)status.textContent=result?.ok?`Continue in your browser to sign in with ${result.provider}.`:`Sign-in error: ${result?.message||'Unable to open sign-in'}`}));
$('#signout')?.addEventListener('click',()=>{sessionStorage.removeItem('fluxExtensionUser');showExtensionStudio()});$('#createExtension')?.addEventListener('click',()=>{const name=prompt('Extension name');if(!name)return;const description=prompt('What does your extension do?')||'';const items=JSON.parse(localStorage.getItem('fluxExtensions')||'[]');items.push({name,description});localStorage.setItem('fluxExtensions',JSON.stringify(items));renderExtensions()});showExtensionStudio();
const terminalOutput=$('#terminalOutput'),terminalInput=$('#terminalInput');
$('#terminalStart')?.addEventListener('click',async()=>{const r=await window.fluxStudio?.startTerminal();if(r?.ok){terminalOutput.textContent='PowerShell started.\n';terminalInput?.focus()}else terminalOutput.textContent=`Terminal error: ${r?.message||'Unable to start terminal'}`});$('#terminalStop')?.addEventListener('click',()=>window.fluxStudio?.stopTerminal());terminalInput?.addEventListener('keydown',e=>{if(e.key==='Enter'){window.fluxStudio?.sendTerminalInput(terminalInput.value+'\r\n');terminalInput.value=''}});window.fluxStudio?.onTerminalData(data=>{terminalOutput.textContent+=data;terminalOutput.scrollTop=terminalOutput.scrollHeight});window.fluxStudio?.onTerminalExit(code=>{terminalOutput.textContent+=`\n[Terminal exited with code ${code}]`});
const updateButton=$('#updateButton'),updateStatus=$('#updateStatus');let pendingUpdate=false;function setUpdateStatus(text,kind=''){if(updateStatus){updateStatus.textContent=text;updateStatus.dataset.state=kind}}
window.fluxStudio?.onUpdateStatus(data=>{if(!data)return;if(data.status==='checking')setUpdateStatus('Checking for updates…','checking');else if(data.status==='up-to-date')setUpdateStatus(`You’re up to date (${data.version}).`,'success');else if(data.status==='available'){pendingUpdate=true;setUpdateStatus(`Update available: ${data.version}`,'available');if(updateButton){updateButton.textContent='Download update';updateButton.disabled=false}}else if(data.status==='downloading'){setUpdateStatus(`Downloading update… ${Math.max(0,Math.min(100,data.percent||0)).toFixed(0)}%`,'downloading');if(updateButton){updateButton.textContent=`Downloading ${Math.max(0,Math.min(100,data.percent||0)).toFixed(0)}%`;updateButton.disabled=true}}else if(data.status==='downloaded'){pendingUpdate=false;setUpdateStatus(`Update ${data.version} downloaded. Restart to install.`,'downloaded');if(updateButton){updateButton.textContent='Install & restart';updateButton.disabled=false;updateButton.dataset.action='install'}}else if(data.status==='error'){setUpdateStatus(`Update error: ${data.message}`,'error');if(updateButton){updateButton.textContent='Check for updates';updateButton.disabled=false;updateButton.dataset.action='check'}}});
updateButton?.addEventListener('click',async()=>{if(updateButton.dataset.action==='install'){window.fluxStudio?.installUpdate();return}if(pendingUpdate){updateButton.disabled=true;setUpdateStatus('Starting download…','downloading');await window.fluxStudio?.downloadUpdate();return}updateButton.disabled=true;updateButton.dataset.action='check';setUpdateStatus('Checking for updates…','checking');const result=await window.fluxStudio?.checkForUpdates();if(result&&!result.ok){setUpdateStatus(`Update error: ${result.message}`,'error');updateButton.disabled=false}});